image: maven:3-jdk-8

cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && ssh-keyscan -H "$SSH_HOSTNAME" > ~/.ssh/known_hosts'

build:
 stage: build
 services:
 - postgres:latest
 variables:
   POSTGRES_DB : "paymentva"
   POSTGRES_USER: "tazkiava"
   POSTGRES_PASSWORD: "HBQD1KLFmjfD3GjeMkLS"
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/paymentva
 script:
 - mvn clean package
 artifacts:
     paths:
       - target/*.jar