image: alpine:latest

cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

build:
 stage: build
 image: maven:3-jdk-8
 script:
 - mvn clean package -DskipTests

deploy-dev:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
