image: maven:3-jdk-8

cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && ssh-keyscan -H "$SSH_HOSTNAME" > ~/.ssh/known_hosts'
  - scp root@$SSH_HOSTNAME:~/bni-ecollection-1.0.0.jar /tmp/
  - mvn deploy:deploy-file -DgroupId=id.co.bni.ecollection -DartifactId=bni-ecollection -Dversion=1.0.0 -Durl=file://$PWD/.mvn/repository/ -Dfile=/tmp/bni-ecollection-1.0.0.jar

build:
 stage: build
 script:
 - mvn clean package -DskipTests

deploy-dev:
 stage: deploy
 variables:
   HEROKU_API_KEY: $HEROKU_API_KEY
 script:
 - mvn heroku:deploy -Dheroku.appName=$HEROKU_APP_NAME -DskipTests